package database;


import model.Execution;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Created by PBanasiak on 3/21/2016.
 */

public interface ExecutionDAO {
    @Transactional(propagation = Propagation.REQUIRED)
    public KeyHolder addExecutionToDatabaseAndReturnAutoGeneratedKey(int idBuyer, int idSeller, int quantity);
    @Transactional(propagation = Propagation.REQUIRED)
    public List<Execution> getAllExecutions();
}
