package database;


import model.Execution;
import java.util.List;

/**
 * Created by PBanasiak on 3/21/2016.
 */

public interface ExecutionDAO {
    public int addExecutionToDatabaseAndReturnAutoGeneratedKey(int idBuyer, int idSeller, int quantity);

    public List<Execution> getAllExecutions();
}
