package database;


import org.springframework.jdbc.support.KeyHolder;

/**
 * Created by PBanasiak on 3/21/2016.
 */

public interface ExecutionDAO {
    public KeyHolder addExecutionToDatabaseAndReturnAutoGeneratedKey(int idBuyer, int idSeller, int quantity);
}
