package camel;

import database.ExecutionDAO;
import database.OrderDAO;
import model.Execution;
import org.apache.camel.Exchange;
import org.apache.camel.Message;
import org.apache.camel.Processor;
import org.apache.camel.impl.DefaultMessage;
import org.springframework.beans.factory.annotation.Autowired;


/**
 * Created by pizmak on 2016-05-11.
 */
public class ExecutionManager implements Processor {
    @Autowired
    ExecutionDAO executionDAO;

    @Autowired
    OrderDAO orderDAO;

    @Override
    public void process(Exchange exchange) throws Exception {
        Execution dateAboutExecution = (Execution) exchange.getIn().getBody();

        exchange.setOut(createExecutionAndCamelMessageAboutExecution(dateAboutExecution));
    }

    public Message createExecutionAndCamelMessageAboutExecution(Execution execution){
        Message messageAboutExecution = new DefaultMessage();

        int idOfExecution = executionDAO.addExecutionToDatabaseAndReturnAutoGeneratedKey(execution.getIdBuyer(),execution.getIdSeller(),execution.getQuantityOfExecution());

        messageAboutExecution.setBody("exec_id"+idOfExecution+"sell_id"+execution.getIdSeller()+"buy_id"+execution.getIdBuyer()+"qty"+execution.getQuantityOfExecution());

        updateOrderToDatabase(execution.getIdBuyer(),execution.getQuantityOfBuyer() - execution.getQuantityOfExecution());
        updateOrderToDatabase(execution.getIdSeller(), execution.getQuantityOfSeller() - execution.getQuantityOfExecution());

        return messageAboutExecution;
    }

    public void updateOrderToDatabase(int idOfOrder, int quantityOfDoneExecution){
        orderDAO.updateOrderToDatabase(idOfOrder,quantityOfDoneExecution);
    }
}
